[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]

serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true

specta = { version = "2.0.0-rc.25", features = ["derive", "uuid", "chrono"] }
specta-typescript = "0.0.12"
specta-serde = "0.0.12"
